# Generated by Django 4.2.4 on 2023-08-10 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_client_client_id_alter_client_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('testimonial_id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='Testimonial ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('designation', models.CharField(max_length=100, verbose_name='Designation')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(upload_to='testimonials/', verbose_name='Image')),
            ],
        ),
    ]
