# Generated by Django 4.2.4 on 2023-08-10 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='title',
            field=models.CharField(default='role', max_length=100),
            preserve_default=False,
        ),
    ]
