# Generated by Django 4.2.4 on 2023-08-11 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_jobapplication_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=200, verbose_name='Blog Title')),
                ('author', models.CharField(max_length=100, verbose_name='Author')),
                ('date', models.TextField(verbose_name='Date')),
                ('featured_image', models.ImageField(upload_to='blogs/', verbose_name='Featured Image')),
                ('description', models.TextField(verbose_name='Job Description')),
            ],
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100, verbose_name='Job Title')),
                ('employee_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Internship', 'Internship')], max_length=20, verbose_name='Employee Type')),
                ('job_location', models.CharField(max_length=100, verbose_name='Job Location')),
                ('required_qualification', models.CharField(max_length=200, verbose_name='Required Qualification')),
                ('required_experience', models.CharField(max_length=50, verbose_name='Required Experience')),
                ('salary', models.CharField(max_length=100, verbose_name='Salary')),
                ('skills', models.CharField(max_length=200, verbose_name='Skills')),
                ('job_description', models.TextField(verbose_name='Job Description')),
                ('roles_responsibilities', models.TextField(verbose_name='Roles and Responsibilities')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=100, verbose_name='Package Name')),
                ('package_type', models.CharField(choices=[('Free', 'Free'), ('Bronze', 'Bronze'), ('Silver', 'Silver'), ('Gold', 'Gold')], max_length=20, verbose_name='Package Type')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('package_details', models.TextField(verbose_name='Package Details')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('portfolio_id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='Portfolio ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('featured_image', models.ImageField(upload_to='ourportfolio/', verbose_name='Featured Image')),
            ],
        ),
    ]
